controller_manager:
  ros__parameters:
    update_rate: 50

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

      publish_limited_velocity: true

      left_wheel_names:  [front_left_wheel_joint, middle_left_wheel_joint, rear_left_wheel_joint]
      right_wheel_names: [front_right_wheel_joint, middle_right_wheel_joint, rear_right_wheel_joint]

      wheel_separation: 0.68
      wheel_radius: 0.1
      cmd_vel_topic: "/cmd_vel"
      publish_rate: 50
      use_stamped_vel: false
      open_loop: false
      pose_publish_period: 0.05

      enable_odom_tf: true
      odom_frame_id: "odom"
      base_frame_id: "base_link"
